name: Greetings

on: 
  pull_request_target:
    types:
      - opened
  issues:
    types:
      - opened

jobs:
  greeting:
    runs-on: ubuntu-latest
    if: ${{ github.actor != 'all-contributors[bot]' && github.event.pull_request.user.login != 'tungbq' }}
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: "Hi, thanks for your contribution! Great first issue!"
          pr-message: "Hi, thanks for your contribution! Great first PR!"
